### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by dilab** [cakephp/docs-theme#1]
Following the installation guide. 

I have added this to my conf.py file:

```
import cakephp_theme

html_theme_path = [cakephp_theme.get_path()]
html_theme = 'cakephp_theme'
extensions = ['cakephp_theme']
```
Then when I run `make html`.

I got the error as shown below:
```
Running Sphinx v1.6.2

Exception occurred:
  File "conf.py", line 84, in <module>
AttributeError: 'module' object has no attribute 'get_path'
```

The full error log is:
```
# Sphinx version: 1.6.2
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/Library/Python/2.7/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/Library/Python/2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 508, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 84, in <module>
AttributeError: 'module' object has no attribute 'get_path'
```

**Comment by josegonzalez** [comment]
Did you `pip install` this theme?

**Comment by dilab** [comment]
yes. I did that as the first thing.

**Comment by josegonzalez** [comment]
I'll take a look at this in a sample project later today.

**Comment by dilab** [comment]
thanks.

**Comment by Helveg** [comment]
I have the same issue now.

**Comment by Helveg** [comment]
@josegonzalez I am facing the same issue.

**Comment by Helveg** [comment]
The fix is to use `get_html_theme_path`. The docs should be updated to reflect this.
